from unittest.mock import patch
from urllib.parse import quote_plus

from odoo.tests.common import tagged

from odoo.addons.pos_conventional_core.tests.common import PosConventionalTestCommon

from ..utils import build_verifactu_receipt_values, get_verifactu_qr_value

AEAT_QR_URL = (
    "https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR"
    "?nif=A39200019&numserie=1%2F000001&fecha=01-01-2025&importe=121.00"
)
QR_IMAGE_URL = (
    f"/report/barcode/?barcode_type=QR&value={quote_plus(AEAT_QR_URL)}"
    "&barLevel=M&width=180&height=180"
)


def _fake_qr_compute(records):
    for record in records:
        record.l10n_es_edi_verifactu_qr_code = QR_IMAGE_URL


def _empty_qr_compute(records):
    for record in records:
        record.l10n_es_edi_verifactu_qr_code = False


class PosConventionalVerifactuTestCommon(PosConventionalTestCommon):
    """Helpers shared by the POS Conventional Veri*Factu receipt tests.

    Veri*Factu documents need certificates and AEAT data, so the QR compute
    is patched with the same URL format generated by l10n_es_edi_verifactu.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.env.company.l10n_es_edi_verifactu_required = True

    def _patch_qr(self, model_name, compute=_fake_qr_compute):
        model_class = type(self.env[model_name])
        patcher = patch.object(
            model_class, "_compute_l10n_es_edi_verifactu_qr_code", compute
        )
        patcher.start()
        self.addCleanup(patcher.stop)
        self.env.invalidate_all()

    def _make_order(self, partner=None):
        if not getattr(self, "_session", None):
            self._session = self._open_session()
        order = self._make_draft_order(self._session, partner)
        self._add_line(order)
        return order

    def _make_invoice(self):
        return self.env["account.move"].create(
            {
                "move_type": "out_invoice",
                "partner_id": self.partner.id,
                "journal_id": self.invoice_journal.id,
                "invoice_line_ids": [
                    (
                        0,
                        0,
                        {
                            "name": "Línea test",
                            "quantity": 1,
                            "price_unit": 100.0,
                        },
                    )
                ],
            }
        )

    def _render(self, report_xmlid, records):
        content, _report_type = self.env["ir.actions.report"]._render_qweb_html(
            report_xmlid, records.ids
        )
        return content.decode() if isinstance(content, bytes) else content


@tagged("pos_conventional_core", "-standard", "post_install", "-at_install")
class TestVerifactuUtils(PosConventionalTestCommon):
    def test_qr_value_is_extracted_from_native_image_url(self):
        self.assertEqual(get_verifactu_qr_value(QR_IMAGE_URL), AEAT_QR_URL)

    def test_qr_value_empty_without_url_or_value(self):
        self.assertEqual(get_verifactu_qr_value(False), "")
        self.assertEqual(get_verifactu_qr_value("/report/barcode/?barcode_type=QR"), "")

    def test_build_values_without_qr_returns_empty_dict(self):
        self.assertEqual(build_verifactu_receipt_values("F1", True, False), {})

    def test_build_values_with_qr(self):
        values = build_verifactu_receipt_values("F1", 1, QR_IMAGE_URL)
        self.assertEqual(
            values,
            {
                "invoice_name": "F1",
                "is_simplified": True,
                "qr_code": QR_IMAGE_URL,
                "qr_value": AEAT_QR_URL,
            },
        )


@tagged("pos_conventional_core", "-standard", "post_install", "-at_install")
class TestVerifactuReceiptValues(PosConventionalVerifactuTestCommon):
    def test_order_not_required_returns_empty(self):
        self._patch_qr("pos.order")
        order = self._make_order()
        self.env.company.l10n_es_edi_verifactu_required = False
        self.assertEqual(order._get_pos_conventional_verifactu_receipt_values(), {})

    def test_order_without_qr_returns_empty(self):
        self._patch_qr("pos.order", _empty_qr_compute)
        order = self._make_order()
        self.assertEqual(order._get_pos_conventional_verifactu_receipt_values(), {})

    def test_order_not_invoiced_uses_native_invoice_name(self):
        self._patch_qr("pos.order")
        order = self._make_order()
        values = order._get_pos_conventional_verifactu_receipt_values()
        self.assertEqual(
            values["invoice_name"], order.l10n_es_edi_verifactu_get_invoice_name()
        )
        self.assertTrue(values["is_simplified"])
        self.assertEqual(values["qr_code"], QR_IMAGE_URL)
        self.assertEqual(values["qr_value"], AEAT_QR_URL)

    def test_refund_order_is_simplified_only_with_r5(self):
        self._patch_qr("pos.order")
        refunded = self._make_order()
        refund = self._make_order(self.partner)
        refund.write(
            {
                "refunded_order_id": refunded.id,
                "l10n_es_edi_verifactu_refund_reason": "R1",
            }
        )
        self.assertFalse(
            refund._get_pos_conventional_verifactu_receipt_values()["is_simplified"]
        )
        refund.l10n_es_edi_verifactu_refund_reason = "R5"
        self.assertTrue(
            refund._get_pos_conventional_verifactu_receipt_values()["is_simplified"]
        )

    def test_invoiced_order_uses_invoice_values(self):
        self._patch_qr("account.move")
        order = self._make_order(self.partner)
        invoice = self._make_invoice()
        order.account_move = invoice
        values = order._get_pos_conventional_verifactu_receipt_values()
        self.assertEqual(values["invoice_name"], invoice.name or "")
        self.assertEqual(values["is_simplified"], invoice.l10n_es_is_simplified)
        self.assertEqual(values["qr_value"], AEAT_QR_URL)

    def test_invoice_not_required_returns_empty(self):
        self._patch_qr("account.move")
        invoice = self._make_invoice()
        self.env.company.l10n_es_edi_verifactu_required = False
        self.assertEqual(invoice._get_pos_conventional_verifactu_receipt_values(), {})


@tagged("pos_conventional_core", "-standard", "post_install", "-at_install")
class TestVerifactuReceiptReports(PosConventionalVerifactuTestCommon):
    def _assert_verifactu_block(self, html):
        self.assertIn("pos-conventional-verifactu", html)
        self.assertIn("QR tributario:", html)
        self.assertIn("VERI*FACTU", html)
        self.assertIn("barcode_type=QR", html)
        self.assertLess(html.index("QR tributario:"), html.index("Gracias por"))

    def test_pos_order_report_prints_verifactu_block(self):
        self._patch_qr("pos.order")
        order = self._make_order()
        html = self._render(
            "pos_conventional_receipt_custom.action_report_pos_order_80mm", order
        )
        self._assert_verifactu_block(html)
        self.assertIn(order.l10n_es_edi_verifactu_get_invoice_name(), html)

    def test_pos_order_report_without_qr_has_no_block(self):
        self._patch_qr("pos.order", _empty_qr_compute)
        order = self._make_order()
        html = self._render(
            "pos_conventional_receipt_custom.action_report_pos_order_80mm", order
        )
        self.assertNotIn("pos-conventional-verifactu", html)

    def test_simplified_invoice_report_prints_verifactu_block(self):
        self._patch_qr("account.move")
        invoice = self._make_invoice()
        html = self._render(
            "pos_conventional_receipt_custom.action_factura_simplificada_80mm", invoice
        )
        self._assert_verifactu_block(html)

    def test_simplified_invoice_report_without_verifactu_has_no_block(self):
        self._patch_qr("account.move")
        invoice = self._make_invoice()
        self.env.company.l10n_es_edi_verifactu_required = False
        html = self._render(
            "pos_conventional_receipt_custom.action_factura_simplificada_80mm", invoice
        )
        self.assertNotIn("pos-conventional-verifactu", html)
